### ISSUE TITLE
Further clarification AppTutorial.md

### ISSUE THREAD

**Issue by emieldesmidt** [Tribler/trustchain-superapp#1]
The repository is set up using submodules, however this hinders us from locally installing the app (even using the `--recursive` flag). Log indicates the following issue: `Host key verification failed`. Current workaround is loading the module manually, but this raises further errors.

If you could help us out, that would be appreciated. Furthermore would be nice to see a note on this in the `AppTutorial.md` file.

**Comment by MattSkala** [comment]
You should be able to clone the repository including submodules using the `--recursive` flag. If you already cloned the repository, you can initialize submodules using `git submodule update --init`.

I'm not sure about the host verification failed error you receive though. It could be that you do not have the github.com's ssh public key in your known hosts. In that case, you can add it using the following command:
`ssh-keyscan github.com >> ~/.ssh/known_hosts`

**Comment by emieldesmidt** [comment]
Fixed, for those encountering the same issue, don't forget to add an ssh-key to your github account: https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
