### ISSUE TITLE
Trustchain: Native Android implementation

### ISSUE THREAD

**Issue by synctext** [Tribler/trustchain-superapp#44]
Create a clean-slate Java implementation of Trustchain. Enables future support of a  Android credit wallet. Plus future digital votingpass app future integration, Tribler/tribler#2918

Issues:
- compatible with the Tribler credit in the wild, new Alpha release format: https://github.com/qstokkink/py-ipv8/blob/master/README.md.
- http://trustchain-android.readthedocs.org
- Sign and create transactions blocks on local created Trustchain (e.g. signed Hello World!)
- import into local SQLight
- Android-to-Android sign transactions with nearby devices (wifi or Bluetooth)
- Try to re-use some code of this prior project: https://github.com/ericcornelissen/NervousFish
- Download and browse Trustchain blocks for any selected public key
- Can we also support the Brainpool elliptic curve of the Dutch Passport?

First results:
![screenshot_2017-09-19-13-57-00](https://user-images.githubusercontent.com/325224/30591897-f8dabcfe-9d44-11e7-9186-1a046cd36b5f.png)

**Comment by devos50** [comment]
This issue is indeed completed so I will close it 👍
